---
- name: TLS | Check target bundle type
  fail:
    msg: "Your tls.target_format is not supported"
  when: tls.target_format not in ["haproxy", "nginx"]

- name: TLS | Ensure directories
  become: yes
  become_user: root
  file:
    path: "{{ tls.target_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755